branch-defaults:
  main:
    environment: Ai-voice-assistant-test-env
environment-defaults:
  Ai-voice-assistant-test-env:
    branch: null
    repository: null
global:
  application_name: ai-voice-assistant-test
  default_ec2_keyname: null
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
